spring:
  application:
    name: MindingMyBookness
  datasource:
    url: jdbc:postgresql://localhost:5432/mindingmybookness_database
    username: ahmad
    password: ilovejava

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
    port: 8090