spring:
  application:
    name: MindingMyBookness
  datasource:
    url: jdbc:postgresql://localhost:5432/mindingmybookness_database
    username: ahmad
    password: ilovejava

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
    port: 8090

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY:cml2ZXJleGFjdGx5Y29uc2lkZXJpbXBvcnRhbmNlc3VnYXJsYXN0d2hhdHdlaWdoZmw==}